### ISSUE TITLE
Add tasks descriptions to analysis YAML file

### ISSUE THREAD

**Issue by Kraysent** [Kraysent/Galactic-archeology#30]

**Comment by Kraysent** [comment]
Example: 
```yaml
# Velocity profile plot
  - coords: [0.18, 0, 0.32, 0.3]
    params: 
      xlim: [0, 15]
      ylim: [0, 400]
      xlabel: '$r$, kpc'
      ylabel: '$v$, km/s'
      grid: True
    tasks:
      - name: VelocityProfileTask
        args: {}
        slice: !link 'host.slice'
        display:
          linestyle: solid
          color: !link 'host.color'
          marker: 'None'
          label: !link 'host.name'
      - name: VelocityProfileTask
        args: {}
        slice: !link 'satellite.slice'
        display:
          linestyle: solid
          color: !link 'satellite.color'
          marker: 'None'
          label: !link 'satellite.name'
      - name: VelocityProfileTask
        args: {}
        display:
          linestyle: solid
          color: y
          marker: 'None'
          label: all
```

**Comment by Kraysent** [comment]
To make it less clunky there should probably be default display parameters associated with each task (for example, solid lines for profile tasks and dots for scatter tasks).

**Comment by Kraysent** [comment]
Analysis config file should also contain descriptions of objects, for example: 
```yaml
objects:
  - name: host
    color: b
    slice: [0, 1000000]
  - name: satellite
    color: r
    slice: [1000001, 1500002]
```
